# Generated by Django 5.0.3 on 2024-03-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
